/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GlobalDialog: typeof import('./components/GlobalDialog.vue')['default']
    GlobalLoading: typeof import('./components/GlobalLoading.vue')['default']
    GlobalMessage: typeof import('./components/GlobalMessage.vue')['default']
    GlobalToast: typeof import('./components/GlobalToast.vue')['default']
    PrivacyPopup: typeof import('./components/PrivacyPopup.vue')['default']
    SkeletonPage: typeof import('./components/SkeletonPage.vue')['default']
    StatusBadge: typeof import('./components/StatusBadge.vue')['default']
  }
}
