/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GlobalDialog: typeof import('./components/GlobalDialog.vue')['default']
    GlobalLoading: typeof import('./components/GlobalLoading.vue')['default']
    GlobalMessage: typeof import('./components/GlobalMessage.vue')['default']
    GlobalToast: typeof import('./components/GlobalToast.vue')['default']
    PrivacyPopup: typeof import('./components/PrivacyPopup.vue')['default']
    SkeletonPage: typeof import('./components/SkeletonPage.vue')['default']
    StatusBadge: typeof import('./components/StatusBadge.vue')['default']
    WdActionSheet: typeof import('@wot-ui/ui/components/wd-action-sheet/wd-action-sheet.vue')['WdActionSheet']
    WdAvatar: typeof import('@wot-ui/ui/components/wd-avatar/wd-avatar.vue')['WdAvatar']
    WdButton: typeof import('@wot-ui/ui/components/wd-button/wd-button.vue')['WdButton']
    WdCell: typeof import('@wot-ui/ui/components/wd-cell/wd-cell.vue')['WdCell']
    WdCellGroup: typeof import('@wot-ui/ui/components/wd-cell-group/wd-cell-group.vue')['WdCellGroup']
    WdCheckbox: typeof import('@wot-ui/ui/components/wd-checkbox/wd-checkbox.vue')['WdCheckbox']
    WdCol: typeof import('@wot-ui/ui/components/wd-col/wd-col.vue')['WdCol']
    WdCollapse: typeof import('@wot-ui/ui/components/wd-collapse/wd-collapse.vue')['WdCollapse']
    WdCollapseItem: typeof import('@wot-ui/ui/components/wd-collapse-item/wd-collapse-item.vue')['WdCollapseItem']
    WdConfigProvider: typeof import('@wot-ui/ui/components/wd-config-provider/wd-config-provider.vue')['WdConfigProvider']
    WdDialog: typeof import('@wot-ui/ui/components/wd-dialog/wd-dialog.vue')['WdDialog']
    WdDivider: typeof import('@wot-ui/ui/components/wd-divider/wd-divider.vue')['WdDivider']
    WdDropMenu: typeof import('@wot-ui/ui/components/wd-drop-menu/wd-drop-menu.vue')['WdDropMenu']
    WdDropMenuItem: typeof import('@wot-ui/ui/components/wd-drop-menu-item/wd-drop-menu-item.vue')['WdDropMenuItem']
    WdEmpty: typeof import('@wot-ui/ui/components/wd-empty/wd-empty.vue')['WdEmpty']
    WdFab: typeof import('@wot-ui/ui/components/wd-fab/wd-fab.vue')['WdFab']
    WdForm: typeof import('@wot-ui/ui/components/wd-form/wd-form.vue')['WdForm']
    WdFormItem: typeof import('@wot-ui/ui/components/wd-form-item/wd-form-item.vue')['WdFormItem']
    WdGap: typeof import('@wot-ui/ui/components/wd-gap/wd-gap.vue')['WdGap']
    WdIcon: typeof import('@wot-ui/ui/components/wd-icon/wd-icon.vue')['WdIcon']
    WdImagePreview: typeof import('@wot-ui/ui/components/wd-image-preview/wd-image-preview.vue')['WdImagePreview']
    WdImg: typeof import('@wot-ui/ui/components/wd-img/wd-img.vue')['WdImg']
    WdInput: typeof import('@wot-ui/ui/components/wd-input/wd-input.vue')['WdInput']
    WdLoading: typeof import('@wot-ui/ui/components/wd-loading/wd-loading.vue')['WdLoading']
    WdNavbar: typeof import('@wot-ui/ui/components/wd-navbar/wd-navbar.vue')['WdNavbar']
    WdNotify: typeof import('@wot-ui/ui/components/wd-notify/wd-notify.vue')['WdNotify']
    WdPicker: typeof import('@wot-ui/ui/components/wd-picker/wd-picker.vue')['WdPicker']
    WdPopup: typeof import('@wot-ui/ui/components/wd-popup/wd-popup.vue')['WdPopup']
    WdRadio: typeof import('@wot-ui/ui/components/wd-radio/wd-radio.vue')['WdRadio']
    WdRadioGroup: typeof import('@wot-ui/ui/components/wd-radio-group/wd-radio-group.vue')['WdRadioGroup']
    WdRow: typeof import('@wot-ui/ui/components/wd-row/wd-row.vue')['WdRow']
    WdSearch: typeof import('@wot-ui/ui/components/wd-search/wd-search.vue')['WdSearch']
    WdSkeleton: typeof import('@wot-ui/ui/components/wd-skeleton/wd-skeleton.vue')['WdSkeleton']
    WdSlider: typeof import('@wot-ui/ui/components/wd-slider/wd-slider.vue')['WdSlider']
    WdStep: typeof import('@wot-ui/ui/components/wd-step/wd-step.vue')['WdStep']
    WdSteps: typeof import('@wot-ui/ui/components/wd-steps/wd-steps.vue')['WdSteps']
    WdSwipeAction: typeof import('@wot-ui/ui/components/wd-swipe-action/wd-swipe-action.vue')['WdSwipeAction']
    WdSwitch: typeof import('@wot-ui/ui/components/wd-switch/wd-switch.vue')['WdSwitch']
    WdTab: typeof import('@wot-ui/ui/components/wd-tab/wd-tab.vue')['WdTab']
    WdTabbar: typeof import('@wot-ui/ui/components/wd-tabbar/wd-tabbar.vue')['WdTabbar']
    WdTabbarItem: typeof import('@wot-ui/ui/components/wd-tabbar-item/wd-tabbar-item.vue')['WdTabbarItem']
    WdTabs: typeof import('@wot-ui/ui/components/wd-tabs/wd-tabs.vue')['WdTabs']
    WdTag: typeof import('@wot-ui/ui/components/wd-tag/wd-tag.vue')['WdTag']
    WdText: typeof import('@wot-ui/ui/components/wd-text/wd-text.vue')['WdText']
    WdTextarea: typeof import('@wot-ui/ui/components/wd-textarea/wd-textarea.vue')['WdTextarea']
    WdToast: typeof import('@wot-ui/ui/components/wd-toast/wd-toast.vue')['WdToast']
    WdUpload: typeof import('@wot-ui/ui/components/wd-upload/wd-upload.vue')['WdUpload']
  }
}
