/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/academy/detail" |
  "/pages/academy/index" |
  "/pages/ai/index" |
  "/pages/analysis/index" |
  "/pages/case/analysis" |
  "/pages/case/create" |
  "/pages/case/detail" |
  "/pages/case/fill" |
  "/pages/case/time" |
  "/pages/case/timeline" |
  "/pages/daily-report/index" |
  "/pages/ecg/detail" |
  "/pages/ecg/index" |
  "/pages/ecg/upload" |
  "/pages/followup/detail" |
  "/pages/followup/index" |
  "/pages/login/index" |
  "/pages/meeting/index" |
  "/pages/meeting/preview" |
  "/pages/mine/index" |
  "/pages/selfcheck/index" |
  "/pages/unit/index" |
  "/pages/work/index" |
  "/pages/login/forget/index" |
  "/pages/login/register/index" |
  "/subPages/about/index" |
  "/subPages/setting/index" |
  "/subPages/module_ai/ai-models/index" |
  "/subPages/module_ai/chat/index" |
  "/subPages/module_cpx/announcement-detail/index" |
  "/subPages/module_system/notices/index" |
  "/subPages/module_system/profile/index" |
  "/subPages/module_system/ticket-detail/index" |
  "/subPages/module_system/tickets/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/ai/index" | "/pages/mine/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
